import { FormEvent, useState } from "react";
import { ArrowLeft, ArrowUpRight, LockKeyhole } from "lucide-react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { api } from "../api/client";
import { Button } from "../components/ui/Button";
type LoginResponse = { data: { accessToken: string; refreshToken: string } };
export function LoginPage() {
  const navigate = useNavigate(); const [params] = useSearchParams(); const [email, setEmail] = useState("client1@archer.local"); const [password, setPassword] = useState("ArcherDemo123!"); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const isRegister = params.get("mode") === "register";
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); setLoading(true); try { const result = await api<LoginResponse>(`/api/v1/auth/${isRegister ? "register" : "login"}`, { method: "POST", body: JSON.stringify(isRegister ? { email, password, role: "CLIENT", displayName: email.split("@")[0] } : { email, password }) }); localStorage.setItem("archer_access_token", result.data.accessToken); localStorage.setItem("archer_refresh_token", result.data.refreshToken); navigate("/"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Something went wrong"); } finally { setLoading(false); } }
  return <div className="auth-page"><div className="auth-panel"><Link to="/" className="back-link"><ArrowLeft size={16} />Back to Archer</Link><div className="auth-content"><div className="auth-icon"><LockKeyhole size={21} /></div><div className="eyebrow dark"><span className="eyebrow-dot" />Welcome to Archer</div><h1>{isRegister ? "Start your next chapter." : "Welcome back."}</h1><p>{isRegister ? "Create an account and find a better way to get work done." : "Sign in to continue to your Archer workspace."}</p><form onSubmit={submit} className="auth-form"><label>Email address<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label>Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} required minLength={8} /></label>{error && <div className="form-error">{error}</div>}<Button type="submit" className="full-button" disabled={loading}>{loading ? "Loading…" : isRegister ? "Create account" : "Sign in"} <ArrowUpRight size={16} /></Button></form><div className="demo-hint">Demo account prefilled<br /><strong>client1@archer.local</strong> · <strong>ArcherDemo123!</strong></div></div></div><div className="auth-aside"><div className="auth-quote">“The best work happens when talented people have the space and trust to do it well.”</div><span>— The Archer team</span></div></div>;
}
