import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import App from "./App";
import { I18nProvider } from "./i18n/I18nProvider";
import "./index.css";
import "./connection.css";
import "./i18n.css";
const queryClient = new QueryClient({ defaultOptions: { queries: { staleTime: 30_000, retry: 1 } } });
createRoot(document.getElementById("root")!).render(<StrictMode><I18nProvider><QueryClientProvider client={queryClient}><App /></QueryClientProvider></I18nProvider></StrictMode>);
